openapi: 3.0.0
info:
  title: Omnibiz EPOS API Docs
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: https://api-dev.omnibiz.app
    description: Development server
  # - url: https://api-uat.omnibiz.app
  #   description: UAT server
  # 
paths:
  /retaillog/api/Retailer/SendOTP:
    post:
      tags: 
        - Authentication Service
      summary: Sends an OTP to retailer's phone number and email
      # description: Optional extended description in CommonMark or HTML.
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/SendOTPRequestModel'
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /retailstore/api/Login/Authenticate:
    post:
      tags: 
        - Authentication Service
      summary: Authenticates Retailer
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/SendOTPRequestModel'
      responses:
        '200':    # status code
          # description: A JSON array of user names
          content:
            application/json:
              schema: 
                oneOf:
                - $ref: '#/components/schemas/SendOTPResponseModel'
components:
  schemas:
    SendOTPRequestModel:
      type: object
      properties:
        phone:
          type: string
          required: true
        otpMode:
          type: string
          enum: ["SMS", "PASSWORD"] 
          required: true
        source:
          type: string
          enum: ["Login"]
          required: true
    SendOTPResponseModel:
      type: object
      properties:
        Data:
          type: object
          properties: 
            Details:
              type: array
              items:
                type: object
                properties: 
                  ResultCode:
                    type: number
                    enum: [1, 0]
                  Result:
                    type: string
                  ResultStatus:
                    type: string
        Version:
          type: string
        DateTime:
          type: string
        ResponseType:
          type: string
        Message:
          type: string
        MessageTitle:
          type: string
        Errors:
          type: array
            item:
              type: string
        StatusCode:
          type: string
    AuthenticateModel:
      type: object
      properties:
        loginId:
          type: string
          required: true
        otp:
          type: number
        GrantType:
          type: string
          enum: ["OTP"]
          required: true
        source:
          type: string
          enum: ["Login"]
          required: true
