openapi: 3.0.0
info:
  title: Omnibiz EPOS API Docs
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: https://api-dev.omnibiz.app
    description: Development server
  # - url: https://api-uat.omnibiz.app
  #   description: UAT server
  # 
paths:
  /retaillog/api/Retailer/SendOTP:
    post:
      tags: 
        - Authentication Service
      summary: Sends an OTP to retailer's phone number and email
      # description: Optional extended description in CommonMark or HTML.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendOTPRequestModel'
      responses:
        '200':    # status code
          # description: A JSON array of user names
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/SendOTPResponseModel'
  /retailstore/api/Login/Authenticate/Epos:
    post:
      tags: 
        - Authentication Service
      summary: Authenticate a Retailer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticateRequestModel'
      responses:
        '200':    # status code
          # description: A JSON array of user names
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/AuthenticateResponseModel'
components:
  schemas:
    SendOTPRequestModel:
      type: object
      properties:
        phone:
          type: string
          required: true
        otpMode:
          type: string
          enum: ["SMS", "WhatsApp"] 
          required: true
        source:
          type: string
          enum: ["Login"]
          required: true
    SendOTPResponseModel:
      type: object
      properties:
        Data:
          type: object
          properties: 
            Details:
              type: array
              items:
                type: object
                properties: 
                  ResultCode:
                    type: number
                    enum: [1, 0]
                  Result:
                    type: string
                  ResultStatus:
                    type: string
        Version:
          type: string
        DateTime:
          type: string
        ResponseType:
          type: string
        Message:
          type: string
        MessageTitle:
          type: string
        Errors:
          type: array
          items:
            type: string
        StatusCode:
          type: string
    AuthenticateRequestModel:
      type: object
      properties:
        loginId:
          type: string
          required: true
        otp:
          type: number
          required: true
        GrantType:
          type: string
          enum: ["OTP", "PASSWORD"]
          required: true
        source:
          type: string
          enum: ["Login"]
          required: true
    AuthenticateResponseModel:
      type: object
      properties:
        Data:
          type: object
          properties: 
            RetailId:
              type: number
              example: 9784879
            RetailName:
              type: string
              example: No name
            CountryId:
              type: number
              example: 1
            CountryName:
              type: string
            StateId:
              type: number
            StateName:
              type: string
            CityId:
              type: number
            CityName:
              type: string
            TownId:
              type: number
            TownName:
              type: string
            AccessToken:
              type: string
              example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJCdXNpbmVzc0lkIjoiNzYiLCJVc2VySWQiOiI0NTA
            RefreshToken:
              type: string
              example: 8a78a131-3e5e-46c4-ae75-8157bd7
            Expires:
              type: string
            Email:
              type: string
            Phone:
              type: string
        Version:
          type: string
        DateTime:
          type: string
        ResponseType:
          type: string
        Message:
          type: string
        MessageTitle:
          type: string
        Errors:
          type: array
          items:
            type: string
        StatusCode:
          type: string
