openapi: 3.0.0
info:
  title: Omnibiz EPOS API Docs
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  oneOf:
    - url: https://api-dev.omnibiz.app
    description: Development server
    - url: https://api-uat.omnibiz.app
      description: UAT server
paths:
  /retaillog/api/Retailer/SendOTP:
    get:
      tags: 
        - Authentication Service
      summary: Sends an OTP to retailer's phone number and email
      # description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
components:
  schemas:
    SendOTPModel:
      phone:
        - type: string
      otpMode:
        - type: string
        - enum: ["SMS", "PASSWORD"]
      phone:
        - type: string
      source:
        - type: string
        -
